name: Publish new version
run-name: Publish new ${{ inputs.bump }} version from ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Positionals'
        required: true
        type: choice
        default: 'build'
        options:
          - major
          - minor
          - patch
          - build
      publish-docker-image:
        description: "Publish to docker hub"
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Generate Version
        id: generate_version
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          if [ ${{ inputs.bump }} == major ]; then BUMP='premajor'; fi
          if [ ${{ inputs.bump }} == minor ]; then BUMP='preminor'; fi
          if [ ${{ inputs.bump }} == patch ]; then BUMP='prepatch'; fi
          if [ ${{ inputs.bump }} == build ]; then BUMP='prerelease'; fi
          npm version $BUMP --preid gubuild --force-publish --yes
          git push origin ${{ github.ref }}
          echo "version=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Push Git Tag
        run: |
          git push origin ${{ steps.generate_version.outputs.version }}
    outputs:
      version: ${{ steps.generate_version.outputs.version }}
  
  create-release:
    needs: publish-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.publish-version.outputs.version }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.publish-version.outputs.version }}
          release_name: Release - ${{ needs.publish-version.outputs.version }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ needs.publish-version.outputs.version }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    if: ${{ inputs.publish-docker-image == true }}
    needs: publish-version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gulabs/gu-ethstaker-deposit-cli
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          tags: gulabs/gu-ethstaker-deposit-cli:${{ needs.publish-version.outputs.version }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && needs.publish-version.outputs.version || '' }}
            ${{ inputs.build_args }}
